# Generated by Django 3.1.1 on 2020-09-28 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderAmount', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('addressOne', models.CharField(max_length=500)),
                ('addressTwo', models.CharField(max_length=450, null=True)),
                ('city', models.CharField(max_length=350)),
                ('country', models.CharField(max_length=350, null=True)),
                ('orderPhoneNumber', models.CharField(max_length=15)),
                ('otherPhoneNunber', models.CharField(max_length=15, null=True)),
                ('orderemail', models.EmailField(max_length=35, null=True, verbose_name='email')),
                ('orderDate', models.DateTimeField(auto_now=True)),
                ('orderShipped', models.BooleanField(default=False)),
                ('orderTrakingNumber', models.CharField(max_length=550, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
