# Generated by Django 3.1.1 on 2020-09-28 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDetailsName', models.CharField(max_length=250, null=True)),
                ('orderPrice', models.DecimalField(decimal_places=3, max_digits=20)),
                ('orderQuantity', models.CharField(max_length=150, null=True)),
                ('oder_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.products')),
            ],
        ),
    ]
