# Generated by Django 3.1.1 on 2020-09-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(max_length=35, verbose_name='email')),
                ('firstName', models.CharField(max_length=50, null=True)),
                ('lastName', models.CharField(max_length=50, null=True)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('profileImage', models.ImageField(null=True, upload_to='profiles/')),
                ('varificationNumber', models.CharField(max_length=350, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
